theme: minima
title: Marek Jarocinski
description: Personal webpage
subtitle: Marek Jarociński
email: marek.jarocinski at gmail.com
ORCID: 0000-0002-6345-5067
google-scholar: https://scholar.google.com/citations?hl=en&user=qnXlmMgAAAAJ
